package xyz.migoo.framework.mq.core.stream;

import org.junit.jupiter.api.Test;
import xyz.migoo.framework.mq.core.message.AbstractMessage;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * {@link AbstractStreamMessage} 单元测试
 */
class AbstractStreamMessageTest {

    /** 测试用 Stream 消息 */
    static class DemoStreamMessage extends AbstractStreamMessage {
        private String content;

        public String getContent() {
            return content;
        }

        public void setContent(String content) {
            this.content = content;
        }
    }

    @Test
    void isSubclassOfAbstractMessage() {
        assertThat(new DemoStreamMessage()).isInstanceOf(AbstractMessage.class);
    }

    @Test
    void streamKeyRuleUsesClassSimpleName() {
        // Stream Key 生成规则与 Channel 一致：使用类名
        // （RedisMQTemplate.send 以 getChannel() 作为 stream key）
        assertThat(new DemoStreamMessage().getChannel()).isEqualTo("DemoStreamMessage");
    }

    @Test
    void channelIsSimpleNameNotFullyQualified() {
        assertThat(new DemoStreamMessage().getChannel()).doesNotContain(".").isEqualTo("DemoStreamMessage");
    }

    @Test
    void messageIdAutoGenerated() {
        AbstractStreamMessage message = new DemoStreamMessage();
        assertThat(message.getMessageId()).isNotBlank();
    }

    @Test
    void headersSupportAddAndGet() {
        AbstractStreamMessage message = new DemoStreamMessage();
        message.addHeader("retry-count", "2");
        assertThat(message.getHeader("retry-count")).isEqualTo("2");
        assertThat(message.getHeaders()).containsEntry("retry-count", "2");
    }
}
