package xyz.migoo.framework.mq.core.pubsub;

import org.junit.jupiter.api.Test;
import xyz.migoo.framework.mq.core.message.AbstractMessage;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * {@link AbstractChannelMessage} 单元测试
 */
class AbstractChannelMessageTest {

    /** 测试用 Channel 消息 */
    static class DemoChannelMessage extends AbstractChannelMessage {
        private String content;

        public String getContent() {
            return content;
        }

        public void setContent(String content) {
            this.content = content;
        }
    }

    @Test
    void isSubclassOfAbstractMessage() {
        // 继承自 AbstractMessage，具备 messageId/headers 能力
        assertThat(new DemoChannelMessage()).isInstanceOf(AbstractMessage.class);
    }

    @Test
    void channelDefaultsToClassSimpleName() {
        // channel 默认值规则：类名
        assertThat(new DemoChannelMessage().getChannel()).isEqualTo("DemoChannelMessage");
    }

    @Test
    void channelIsSimpleNameNotFullyQualified() {
        String channel = new DemoChannelMessage().getChannel();
        // 不包含包名，直接是简单类名
        assertThat(channel).isEqualTo("DemoChannelMessage");
        assertThat(channel).doesNotContain(".");
    }

    @Test
    void messageIdAutoGenerated() {
        AbstractChannelMessage message = new DemoChannelMessage();
        assertThat(message.getMessageId()).isNotBlank();
    }

    @Test
    void headersSupportAddAndGet() {
        AbstractChannelMessage message = new DemoChannelMessage();
        message.addHeader("trace-id", "t-1");
        assertThat(message.getHeader("trace-id")).isEqualTo("t-1");
        assertThat(message.getHeaders()).containsKey("trace-id");
    }
}
